/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理员登录 */
        post: operations["loginAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前管理员 */
        get: operations["getCurrentAdministrator"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注销当前管理员会话 */
        post: operations["logoutAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询统一练习账本汇总 */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询用户额度与用量 */
        get: operations["listUsageUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询单个用户额度、会话与用量 */
        get: operations["getUsageUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/entitlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改用户套餐、每日额度和权限状态 */
        patch: operations["updateUserEntitlement"];
        trace?: never;
    };
    "/api/admin/realtime/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询 Realtime 会话及临时 Key 关联 */
        get: operations["listRealtimeSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reconciliation/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询本地会话与官方记录匹配结果 */
        get: operations["listReconciliationRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询统一练习账本、SLS 与 Prometheus 连接状态 */
        get: operations["listDataSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/data-sources/aliyun-sls/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 立即读取阿里云 SLS 推理日志并对账 */
        post: operations["syncAliyunOfficialUsage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example admin@unispeaking.local */
            login: string;
            /** Format: password */
            password: string;
        };
        /** @enum {string} */
        AdminRole: "SUPER_ADMIN" | "OPERATIONS" | "TECHNICAL" | "FINANCE" | "AUDITOR";
        AdminMe: {
            /** Format: uuid */
            id: string;
            login: string;
            role: components["schemas"]["AdminRole"];
        };
        ModelUsage: {
            /** Format: int64 */
            response_count: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            input_text_tokens?: number;
            /** Format: int64 */
            input_audio_tokens?: number;
            /** Format: int64 */
            output_text_tokens?: number;
            /** Format: int64 */
            output_audio_tokens?: number;
        };
        UsageSession: {
            session_id: string;
            user_id: string;
            plan_code?: string;
            status: string;
            measured_seconds: number;
            remaining_seconds: number;
            temporary_key_id?: string | null;
            temporary_key_fingerprint?: string | null;
            /** Format: int64 */
            temporary_key_expires_at?: number | null;
            task_uuid?: string | null;
            provider_request_id?: string | null;
            model_usage: components["schemas"]["ModelUsage"];
            official_usage: components["schemas"]["ModelUsage"];
            /** Format: int64 */
            official_duration_ms?: number | null;
            estimated_cost_cny?: string | null;
            pricing_status?: string | null;
            reconciliation_status: string;
            reconciliation_reasons: string[];
            end_reason?: string | null;
        };
        UsageUser: {
            user_id: string;
            display_name: string;
            plan_code: string;
            plan_name: string;
            /** @enum {string} */
            status: "active" | "suspended";
            /** Format: date */
            quota_date: string;
            quota_seconds: number;
            settled_seconds?: number;
            active_elapsed_seconds?: number;
            used_seconds: number;
            remaining_seconds: number;
            reset_at?: number | null;
            active_session_id?: string | null;
            session_count: number;
            sessions: components["schemas"]["UsageSession"][];
            model_usage: components["schemas"]["ModelUsage"];
            official_usage: components["schemas"]["ModelUsage"];
            estimated_cost_cny?: string | null;
            reconciliation_counts: {
                [key: string]: number;
            };
        };
        UpdateUserEntitlementRequest: {
            planCode: string;
            planName: string;
            quotaSeconds: number;
            /** @enum {string} */
            status: "active" | "suspended";
        };
        UserEntitlement: {
            /** Format: uuid */
            user_id: string;
            plan_code: string;
            plan_name: string;
            /** Format: date */
            quota_date: string;
            quota_seconds: number;
            used_seconds: number;
            /** @enum {string} */
            status: "active" | "suspended";
        };
        DashboardSummary: {
            total_users: number;
            active_sessions: number;
            quota_seconds: number;
            used_seconds: number;
            remaining_seconds: number;
            /** Format: int64 */
            client_tokens: number;
            /** Format: int64 */
            official_tokens: number;
            estimated_cost_cny: string;
            reconciliation_pending: number;
            reconciliation_matched: number;
            reconciliation_mismatch: number;
            /** Format: date-time */
            generated_at: string;
        };
        ReconciliationRecord: {
            user_id: string;
            session_id: string;
            temporary_key_id?: string | null;
            task_uuid?: string | null;
            request_id?: string | null;
            /** Format: int64 */
            client_tokens: number;
            /** Format: int64 */
            official_tokens: number;
            client_usage: components["schemas"]["ModelUsage"];
            official_usage: components["schemas"]["ModelUsage"];
            /** Format: int64 */
            official_duration_ms?: number | null;
            estimated_cost_cny?: string | null;
            /** @enum {string} */
            status: "PENDING" | "MATCHED" | "MISMATCH";
            reasons: string[];
        };
        DataSourceState: {
            code: string;
            name: string;
            state: string;
            detail: string;
        };
        OfficialUsageSyncResult: {
            scanned: number;
            accepted: number;
            duplicate: number;
            unbound: number;
            rejected_context: number;
            rejected_schema: number;
            imported: number;
            provider_duplicates: number;
            matched: number;
            unmatched: number;
            /** Format: date-time */
            synced_at: string;
        };
        ErrorBody: {
            /** @example AUTH_INVALID */
            code: string;
            /** @example 用户名或密码错误 */
            message: string;
        };
        ApiError: {
            error: components["schemas"]["ErrorBody"];
            /** Format: uuid */
            request_id: string;
        };
    };
    responses: {
        /** @description 用户名或密码错误；不区分具体失败原因。 */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 会话不存在、已过期或已撤销。 */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 请求字段不符合约束。 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 统一练习账本或官方数据源暂时不可用。 */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 用户不存在。 */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功；服务端创建不透明会话。 */
            204: {
                headers: {
                    /** @description HttpOnly、SameSite=Strict 的管理会话 Cookie。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["InvalidCredentials"];
        };
    };
    getCurrentAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前已登录管理员。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMe"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    logoutAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务端会话已撤销，浏览器 Cookie 已清除。 */
            204: {
                headers: {
                    /** @description Max-Age=0 的过期 Cookie。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前可观测数据汇总。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listUsageUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users: components["schemas"]["UsageUser"][];
                    };
                };
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    getUsageUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageUser"];
                };
            };
            404: components["responses"]["UserNotFound"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    updateUserEntitlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserEntitlementRequest"];
            };
        };
        responses: {
            /** @description 更新后的当天用户权益；当天已用时长保持不变。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntitlement"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            /** @description 当前管理员角色无权修改用户权益。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["UserNotFound"];
        };
    };
    listRealtimeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["UsageSession"][];
                    };
                };
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listReconciliationRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 对账记录。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        records: components["schemas"]["ReconciliationRecord"][];
                    };
                };
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listDataSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 数据源状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sources: components["schemas"]["DataSourceState"][];
                    };
                };
            };
        };
    };
    syncAliyunOfficialUsage: {
        parameters: {
            query?: never;
            header: {
                "X-Admin-Action": "sync-official-usage";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同步结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficialUsageSyncResult"];
                };
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
}
